on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@master
      # - name: copy file via ssh
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.REMOTE_HOST }}
      #     username: ${{ secrets.REMOTE_USERNAME }}
      #     key: ${{ secrets.REMOTE_KEY }}
      #     source: "instruction.txt,instruction.txt"
      #     target: "/root"

      - name: Connect to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_KEY }}
          script: "docker run -i -v $(pwd):/chisel rizaudo/chisel3-docker /bin/bash < test.sh >/dev/null &"
