on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: "ls"
      - run: "pwd"
      - name: pull and run chisel
        run: docker run -i -v $(pwd):/chisel rizaudo/chisel3-docker /bin/bash < build.sh
